### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by YusenFan** [Cicada-S/Forum#1]
hi 你好 我有点没有搞懂PageIndex 当前分页这个变量的意思， 方便的话可以讲解一下吗

**Comment by Cicada-S** [comment]
因为数据不是一次性获取全部的，需要进行分页获取，PageIndex则表示当前的分页。
可以看下面这行代码  就是用当前分页和每次获取的条数 计算出下次获取数据时需要跳过前n条
`const skip = event.pageSize * (event.pageIndex - 1)`
你可以拉一下新的代码，之前的代码分页获取数据时有bug
