### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by MaoloveW** [Cicada-S/Forum#2]
作者大大，您好，请问能否教一下这款小程序需要修改的地方，十分感谢

**Comment by MaoloveW** [comment]
请问，加密猫为什么放到服务器后，不能正常加密解密

**Comment by Cicada-S** [comment]
需要修改的东西我写在了[README.md](https://github.com/Cicada-S/Forum#readme) 你可以看一下

**Comment by Cicada-S** [comment]
> 作者大大，您好，请问能不能教一下这款小程序需要修改的地方，十分感谢

需要修改的东西我写了[README.md](https://github.com/Cicada-S/Forum#readme)你可以看看下
