### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by my12yyds** [Cicada-S/Forum#3]
你好，我是一个新学习微信小程序的学生，我想问一下那个数据库是怎么样的格式内容，我看不是很明白，打扰大佬了

**Comment by Cicada-S** [comment]
> 你好，我是一个新学习微信小程序的学生，我想问一下那个数据库是怎么样的格式内容，我看不是很明白，打扰大佬了
主要是什么问题你可以详细说一下 如果复杂的话可以给我发邮件

**Comment by Cicada-S** [comment]
> 你好，我是一个新学习微信小程序的学生，我想问一下那个数据库是怎么样的格式内容，我看不是很明白，打扰大佬了

主要是什么问题你可以详细说一下 如果复杂的话可以给我发邮件

**Comment by ZoftTy** [comment]
> > 你好，我是一个新学习微信小程序的学生，我想问一下那个数据库是怎么样的格式内容，我看不是很明白，打扰大佬了
> 
> 主要是什么问题你可以详细说一下 如果复杂的话可以给我发邮件

逮到啦

**Comment by my12yyds** [comment]
没事了我解决了，谢谢捏

**Comment by Cicada-S** [comment]
> 没事了我解决了，谢谢捏
好
